# Generated by Django 4.0.2 on 2022-02-08 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_accounts_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='date',
            new_name='transaction_date',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='date',
            new_name='transaction_date',
        ),
        migrations.RenameField(
            model_name='withdraw',
            old_name='date',
            new_name='transaction_date',
        ),
    ]
